[package]
name = "sn32f26x_unlock"
version = "0.1.0"
authors = ["IsaacDynamo"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cortex-m-rt = "0.7.0"
panic-halt = "0.2.0"
cortex-m = "0.7.3"
